src/Entity/Doctor.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\DoctorRepository")
 */
class Doctor
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $firstname;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $lastname;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $photo;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Skill", inversedBy="doctors")
     */
    private $skills;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Appointment", mappedBy="doctor")
     */
    private $appointments;

    public function __construct()
    {
        $this->skills = new ArrayCollection();
        $this->appointments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getPhoto(): ?string
    {
        return $this->photo;
    }

    public function setPhoto(?string $photo): self
    {
        $this->photo = $photo;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    /**
     * @return Collection|Skill[]
     */
    public function getSkills(): Collection
    {
        return $this->skills;
    }

    public function addSkill(Skill $skill): self
    {
        if (!$this->skills->contains($skill)) {
            $this->skills[] = $skill;
        }

        return $this;
    }

    public function removeSkill(Skill $skill): self
    {
        if ($this->skills->contains($skill)) {
            $this->skills->removeElement($skill);
        }

        return $this;
    }

    /**
     * @return Collection|Appointment[]
     */
    public function getAppointments(): Collection
    {
        return $this->appointments;
    }

    public function addAppointment(Appointment $appointment): self
    {
        if (!$this->appointments->contains($appointment)) {
            $this->appointments[] = $appointment;
            $appointment->setDoctor($this);
        }

        return $this;
    }

    public function removeAppointment(Appointment $appointment): self
    {
        if ($this->appointments->contains($appointment)) {
            $this->appointments->removeElement($appointment);
            // set the owning side to null (unless already changed)
            if ($appointment->getDoctor() === $this) {
                $appointment->setDoctor(null);
            }
        }

        return $this;
    }

    public function getFullname(): string
    {
        return $this->getFirstname() . " " . $this->getLastname();
    }

    public function __toString()
    {
        return $this->getFullname();
    }

}

src/Form/DoctorType.php
<?php

namespace App\Form;

use App\Entity\Doctor;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class DoctorType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('firstname')
            ->add('lastname')
            ->add('photo')
            ->add('description')
            ->add('skills')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Doctor::class,
        ]);
    }
}

src/Controller/DoctorController.php
<?php

namespace App\Controller;

use App\Entity\Doctor;
use App\Form\DoctorType;
use App\Repository\DoctorRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/doctor")
 */
class DoctorController extends AbstractController
{
    /**
     * @Route("/", name="doctor_index", methods={"GET"})
     */
    public function index(DoctorRepository $doctorRepository): Response
    {
        return $this->render('doctor/index.html.twig', [
            'doctors' => $doctorRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="doctor_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $doctor = new Doctor();
        $form = $this->createForm(DoctorType::class, $doctor);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($doctor);
            $entityManager->flush();

            return $this->redirectToRoute('doctor_index');
        }

        return $this->render('doctor/new.html.twig', [
            'doctor' => $doctor,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="doctor_show", methods={"GET"})
     */
    public function show(Doctor $doctor): Response
    {
        return $this->render('doctor/show.html.twig', [
            'doctor' => $doctor,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="doctor_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Doctor $doctor): Response
    {
        $form = $this->createForm(DoctorType::class, $doctor);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('doctor_index');
        }

        return $this->render('doctor/edit.html.twig', [
            'doctor' => $doctor,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="doctor_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Doctor $doctor): Response
    {
        if ($this->isCsrfTokenValid('delete'.$doctor->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($doctor);
            $entityManager->flush();
        }

        return $this->redirectToRoute('doctor_index');
    }
}

templates/doctor/_delete_form.html.twig
<form method="post" action="{{ path('doctor_delete', {'id': doctor.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ doctor.id) }}">
    <button class="btn">Delete</button>
</form>

templates/doctor/_thumnail.html.twig
<article class="doctor-thumbnail">
    <img src="{{ asset('uploads/' ~ doctor.photo) }}" alt="{{ doctor.fullname }}">
    <div class="doctor-details">
        <h4>{{ doctor.fullname }}</h4>
        <p class="doctor-skills">
            {% for skill in doctor.skills %}
                <span>{{ skill.label }}</span>
            {% endfor %}
        </p>
        <a href="{{ path('doctor_show', {'id': doctor.id}) }}" class="btn btn-dark">
            <i class="fa fa-eye"></i>
            Plus d'informations
        </a>
    </div>
</article>

templates/doctor/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Doctor{% endblock %}

{% block body %}
    <h1>Edit Doctor</h1>

    {{ include('doctor/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('doctor_index') }}">back to list</a>

    {{ include('doctor/_delete_form.html.twig') }}
{% endblock %}

templates/doctor/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des docteurs{% endblock %}

{% block body %}

    <section class="container">
        <h1>Liste des docteurs</h1>
    </section>

    <section class="doctors">
        <div class="container">
            {% for doctor in doctors %}
                <article class="doctor-thumbnail">
                    <img src="{{ asset('uploads/' ~ doctor.photo) }}" alt="{{ doctor.fullname }}">
                    <div class="doctor-details">
                        <h4>{{ doctor.fullname }}</h4>
                        <p class="doctor-skills">
                            {% for skill in doctor.skills %}
                                <span>{{ skill.label }}</span>
                            {% endfor %}
                        </p>
                        <a href="{{ path('doctor_show', {'id': doctor.id}) }}" class="btn btn-dark">
                            <i class="fa fa-eye"></i>
                            Plus d'informations
                        </a>
                    </div>
                </article>
            {% endfor %}
        </div>
    </section>

{% endblock %}

templates/doctor/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Doctor{% endblock %}

{% block body %}
    <h1>Create new Doctor</h1>

    {{ include('doctor/_form.html.twig') }}

    <a href="{{ path('doctor_index') }}">back to list</a>
{% endblock %}

templates/doctor/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ doctor.fullname }}{% endblock %}

{% block body %}

    <div class="container">
        <h1>{{ doctor.fullname }}</h1>
        <img src="{{ asset('uploads/' ~ doctor.photo) }}" alt="{{ doctor.fullname }}">
        <p>Compétences :</p>
        <ul>
            {% for skill in doctor.skills %}
                <li>{{ skill.label }}</li>
            {% else %}
                <li>Aucune compétence</li>
            {% endfor %}
        </ul>
        <p>{{ doctor.description }}</p>
    </div>

{% endblock %}